#!/bin/bash

dec2ip () {
    local ip delim dec=$@
    for e in {3..0}
    do
        ((octet = dec / (256 ** e) ))
        ((dec -= octet * 256 ** e))
        ip+=$delim$octet
        delim=.
    done
    printf '%s\n' "$ip"
}


CONTAINERS=$1
COMPOSEFILE=$2
rm -f $COMPOSEFILE

printf "# GENERATED BY \"dockerComposeGenerator.sh $CONTAINERS\"\n" >> "$COMPOSEFILE"
printf "version: '3'\n" >> "$COMPOSEFILE"
printf "services:\n" >> "$COMPOSEFILE"
printf "\n" >> "$COMPOSEFILE"

for i in $(seq 1 $CONTAINERS); do 

  # 167837953 is 10.1.1.1
  address=$(dec2ip $((167837953+$i)))

  port=$((40001+$i))

  printf "  cryptoac_proxy_$i:\n" >> "$COMPOSEFILE"
  printf "    networks:\n" >> "$COMPOSEFILE"
  printf "      test:\n" >> "$COMPOSEFILE"
  printf "        ipv4_address: \"$address\"\n" >> "$COMPOSEFILE"
  printf "    image: cryptoac_cryptoac:latest\n" >> "$COMPOSEFILE"
  printf "    ports:\n" >> "$COMPOSEFILE"
  printf "      - \"$port:8443\"\n" >> "$COMPOSEFILE"
  printf "    entrypoint: [ \"/cryptoac/bin/CryptoAC\", \"-op\"]\n" >> "$COMPOSEFILE"
  printf "\n" >> "$COMPOSEFILE"

done

printf "  cryptoac_mosquitto_no_dynsec:\n" >> "$COMPOSEFILE"
printf "    networks:\n" >> "$COMPOSEFILE"
printf "      test:\n" >> "$COMPOSEFILE"
printf "        ipv4_address: \"\${CRYPTOACMOSQUITTOHOSTIP}\"\n" >> "$COMPOSEFILE"
printf "    image: cryptoac_mosquitto_no_dynsec:latest\n" >> "$COMPOSEFILE"
printf "    ports:\n" >> "$COMPOSEFILE"
printf "      - \"\${CRYPTOACMOSQUITTOHOSTPORT}:\${CRYPTOACMOSQUITTOMOSQUITTOPORT}\"\n" >> "$COMPOSEFILE"
printf "\n" >> "$COMPOSEFILE"
printf "  cryptoac_redis:\n" >> "$COMPOSEFILE"
printf "    networks:\n" >> "$COMPOSEFILE"
printf "      test:\n" >> "$COMPOSEFILE"
printf "        ipv4_address: \"\${CRYPTOACREDISHOSTIP}\"\n" >> "$COMPOSEFILE"
printf "    image: cryptoac_redis:latest\n" >> "$COMPOSEFILE"
printf "    ports:\n" >> "$COMPOSEFILE"
printf "      - \"\${CRYPTOACREDISHOSTPORT}:\${CRYPTOACREDISPORT}\"\n" >> "$COMPOSEFILE"
printf "\n" >> "$COMPOSEFILE"
printf "networks:\n" >> "$COMPOSEFILE"
printf "  test:\n" >> "$COMPOSEFILE"
printf "    driver: bridge\n" >> "$COMPOSEFILE"
printf "    ipam:\n" >> "$COMPOSEFILE"
printf "      driver: default\n" >> "$COMPOSEFILE"
printf "      config:\n" >> "$COMPOSEFILE"
printf "        - subnet: 10.1.0.0/16\n" >> "$COMPOSEFILE"
